drop table if exists SDP.T_USER_RIGHTS;
drop table if exists SDP.T_USER_ROLES;
drop table if exists SDP.T_USER;
drop table if exists SDP.T_ACCESS_TOKENS;
drop table if exists SDP.T_ROLES_RIGHTS;
drop table if exists SDP.S_RIGHTS;
drop table if exists SDP.S_ROLES;
drop table if exists SDP.T_APPLICATION_PARAMS;
drop table if exists SDP.T_STATION_SETUP_EQUIPMENTS;
drop table if exists SDP.T_STATION_SETUP;
drop table if exists SDP.T_STATIONS;
drop table if exists SDP.S_EQUIPMENT;
drop table if exists SDP.S_EQUIPMENT_TYPE;
drop table if exists SDP.T_NETWORKS;
drop schema SDP;
